services:
  web:
    container_name: chesscom_web
    image: emilycogsdill/chesscom-helper:latest
    environment:
      - COMMIT_INFO_GIT_SHA=${GIT_SHA:-}
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    env_file: .env
    volumes:
      - ./chesscom_helper:/app
    ports:
      - "8000:8000"
      - "5173:5173"
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "/app/scripts/cmd-web.sh --init-db"]

  db:
    image: postgres:15
    container_name: chesscom_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
