services:
  web:
    container_name: chesscom_web
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - COMMIT_INFO_GIT_SHA=${GIT_SHA:-}
    env_file: .env
    volumes:
      - ./chesscom_helper:/app
    ports:
      - "8000:8000"  # Django backend
      - "5173:5173"  # Vite frontend
    depends_on:
      - db
    command: ["sh", "-c", "/app/scripts/cmd-web.sh --init-db"]
  db:
    image: postgres:15
    container_name: chesscom_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
