name = "chesscom-helper"
main = "src/index.ts"
compatibility_date = "2024-01-15"

# Workers Sites configuration
[site]
bucket = "./public"

# Environment Variables
[vars]
JWT_SECRET = "your-super-secret-jwt-key-change-this-in-production"
ENVIRONMENT = "development"

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "chesscom-helper-db"
database_id = "4b98097e-9152-4056-b6b0-31fbf12152f4"