name = "chesscom-helper"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.development]
name = "chesscom-helper-dev"

[[env.development.d1_databases]]
binding = "DB"
database_name = "chesscom-helper-dev"
database_id = "dev-database-id"

[[env.development.kv_namespaces]]
binding = "CACHE"
id = "dev-cache-namespace"

[env.development.vars]
CHESS_COM_API_URL = "https://api.chess.com/pub"
JWT_SECRET = "dev-jwt-secret-change-in-production"
RESEND_API_KEY = "dev-resend-key"

[[env.development.triggers]]
crons = ["*/5 * * * *"] # Check every 5 minutes

[env.production]
name = "chesscom-helper-prod"

[[env.production.d1_databases]]
binding = "DB"
database_name = "chesscom-helper-production"
database_id = "5abdc148-9c53-420d-b364-c81305c5cc58"

[[env.production.kv_namespaces]]
binding = "CACHE" 
id = "prod-cache-namespace"

[env.production.vars]
CHESS_COM_API_URL = "https://api.chess.com/pub"

[[env.production.triggers]]
crons = ["*/5 * * * *", "0 */6 * * *"] # Monitor every 5 min, cleanup every 6 hours

[env.staging]
name = "chesscom-helper-staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "chesscom-helper-staging"
database_id = "staging-database-id"

[[env.staging.kv_namespaces]]
binding = "CACHE"
id = "staging-cache-namespace"

[env.staging.vars]
CHESS_COM_API_URL = "https://api.chess.com/pub"

[[env.staging.triggers]]
crons = ["*/10 * * * *"] # Check every 10 minutes for staging