name = "chesscom-helper-cron"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Run every 5 minutes
[triggers]
crons = ["*/5 * * * *"]

[vars]
CHESS_COM_API_BASE = "https://api.chess.com/pub"

# Secrets (set separately)
# DATABASE_URL
# EMAIL_API_KEY
# EMAIL_FROM_ADDRESS