# Generated by Django 5.1.5 on 2025-01-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Dummy',
                'verbose_name_plural': 'Dumdums',
                'ordering': ('created_at',),
            },
        ),
    ]
