# Generated by Django 5.1.5 on 2025-02-02 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chesscom_app", "0002_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Dummy",
        ),
    ]
