name = "chesscom-helper"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

# Assets for React frontend
[assets]
bucket = "./dist"
include = ["**/*"]

# Environment variables
[vars]
CHESS_COM_API_BASE = "https://api.chess.com/pub"
FRONTEND_URL = "https://chesscom-helper.emily-flambe.workers.dev"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "chesscom-helper-db"
database_id = "your-database-id-here"

[triggers]
crons = []