# Generated by Django 5.1.5 on 2025-01-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify_me', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('player_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('followers', models.IntegerField(default=0)),
                ('country', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('last_online', models.BigIntegerField()),
                ('joined', models.BigIntegerField()),
                ('status', models.CharField(max_length=50)),
                ('is_streamer', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('league', models.CharField(blank=True, max_length=50, null=True)),
                ('streaming_platforms', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
