name: Setup SSH config for multi-hop

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: false
        default: 'main'

jobs:
  setup-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Create SSH config
        run: |
          cat <<EOF >> ~/.ssh/config
          Host bastion
          HostName "${{ secrets.BASTION_HOST }}"
          User ec2-user
          IdentityFile ~/.ssh/id_rsa

          Host target
            HostName "${{ secrets.TARGET_HOST }}"
            User ec2-user
            IdentityFile ~/.ssh/id_rsa
            ProxyJump bastion
            EOF
